import = ["/home/malthe/.config/alacritty/catppuccin-frappe.toml"]

[font]
size = 14

[font.bold]
family = "Fira Code"
style = "Medium"

[font.bold_italic]
family = "Fira Code"

[font.italic]
family = "Fira Code"

[font.normal]
family = "Fira Code"
style = "Retina"

[font.offset]
x = 0
y = 1

[selection]
save_to_clipboard = true

[window]
decorations = "none"
