theme = "everforest_dark"

[editor]
auto-pairs = false
line-number = "relative"
mouse = false

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
