theme = "catppuccin_frappe"

[editor]
auto-pairs = false
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
mouse = false
rulers = [101]
shell = ["fish", "-c"]
true-color = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.smart-tab]
enable = false

[keys.normal]
J = "half_page_down" 
K = "half_page_up"

X = "extend_line_above"

w = "extend_next_word_start"
W = "extend_next_long_word_start"
C-w = "extend_next_sub_word_start"
b = "extend_prev_word_start"
B = "extend_prev_long_word_start"
C-b = "extend_prev_sub_word_start"
e = "extend_next_word_end"
E = "extend_next_long_word_end"
C-e = "extend_next_sub_word_end"

G = "extend_to_line_end"
0 = "extend_to_line_start"

f = "extend_next_char"
F = "extend_prev_char"
t = "extend_till_char"
T = "extend_till_prev_char"
";" = "repeat_last_motion"

"{" = ["ensure_selections_forward", "flip_selections", "select_mode", "goto_prev_paragraph", "normal_mode"]
"}" = ["ensure_selections_forward", "select_mode", "goto_next_paragraph", "normal_mode"]
"M" = "@map"

D = ["collapse_selection", "extend_to_line_end", "delete_selection"]
C-d = "delete_selection_noyank"
C = ["collapse_selection", "extend_to_line_end", "change_selection"]
C-c = "change_selection_noyank"
Y = ["collapse_selection", "extend_to_line_end", "yank", "flip_selections", "collapse_selection"]

C-y = "yank_to_clipboard"
C-p = "paste_clipboard_after"
C-r = "replace_selections_with_clipboard"

esc = "collapse_selection"
minus = "join_selections_space"
_ = "join_selections"
z = "flip_selections"
Z = "remove_selections"
s = "copy_selection_on_next_line"
S = "select_regex"
q = "split_selection_on_newline"
Q = "keep_selections"

H = "goto_word"
V = "toggle_comments"

tab = ":buffer-next"
S-tab = ":buffer-previous"
C-s = ":write"
C-q = ":buffer-close"
C-x = ":write-buffer-close"
C-u = ":reload-all"
C-t = ":toggle-option soft-wrap.enable"

space = "file_picker"
L = "global_search"

"~" = "switch_case"
"`" = "switch_to_lowercase"

"?" = "command_palette"
backspace = "select_register"

"'" = "replay_macro"
"\"" = "record_macro"

down = ["delete_selection", "move_visual_line_down", "paste_before"]
up = ["delete_selection", "move_visual_line_up", "paste_before"]
left = ["delete_selection", "move_char_left", "paste_before"]
right = ["delete_selection", "paste_after"]

"=" = ":pipe-to zellij_repl %{language}"

[keys.select]
G = "extend_to_line_end"
0 = "extend_to_line_start"

f = "extend_next_char"
F = "extend_prev_char"
t = "extend_till_char"
T = "extend_till_prev_char"
";" = "repeat_last_motion"

C-w = "extend_next_sub_word_start"
C-b = "extend_prev_sub_word_start"
C-e = "extend_next_sub_word_end"

z = "flip_selections"

"=" = ":pipe-to zellij_repl %{language}"

[keys.insert]
# Apparently the best way to do this,
# https://github.com/helix-editor/helix/discussions/8258
S-tab = ":insert-output echo -ne '\t'"

[keys.normal.ret]
a = "code_action"
d = "diagnostics_picker"
D = "workspace_diagnostics_picker"
h = "select_references_to_symbol_under_cursor"
k = "hover"
s = "symbol_picker"
S = "workspace_symbol_picker"
r = "rename_symbol"
