theme = "catppuccin_frappe"

[editor]
auto-pairs = false
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
mouse = false
rulers = [81]
shell = ["fish", "-c"]
true-color = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
K = "half_page_up" 
J = "half_page_down" 
X = "extend_line_above"
w = "extend_next_word_start"
W = "extend_next_long_word_start"
b = "extend_prev_word_start"
B = "extend_prev_long_word_start"
e = "extend_next_word_end"
E = "extend_next_long_word_end"
S = "copy_selection_on_next_line"
D = ["collapse_selection", "extend_to_line_end", "delete_selection"]
C = ["collapse_selection", "extend_to_line_end", "change_selection"]
z = "flip_selections"
q = "goto_word"
Q = "repeat_last_motion"
"minus" = "join_selections"
"_" = "join_selections_space"
"`" = "toggle_comments"
"esc" = "collapse_selection"
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"
# TODO: Send language with https://github.com/helix-editor/helix/pull/6979
"ret" = ":pipe-to $HOME/.config/tmux/repl.sh"

[keys.select]
# TODO: See above
"ret" = ":pipe-to $HOME/.config/tmux/repl.sh"

[keys.insert]
# Apparently the best way to do this,
# https://github.com/helix-editor/helix/discussions/8258
"S-tab" = ":insert-output echo -ne '\t'"

[keys.normal."space"]
R = "no_op"
"c" = "replace_selections_with_clipboard"
"C" = "replace_selections_with_primary_clipboard"
"q" = "replay_macro"
"Q" = "record_macro"

[keys.normal.";"]
"tab" = "switch_case"
c = "switch_to_lowercase"
C = "switch_to_uppercase"
F = "ensure_selections_forward"
k = "keep_selections"
K = "remove_selections"
m = "merge_selections"
p = "copy_selection_on_next_line"
P = "copy_selection_on_prev_line"
r = "select_regex"
s = "split_selection_on_newline"
S = "split_selection"
