theme = "catppuccin_frappe"

[editor]
auto-pairs = false
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
mouse = false
rulers = [81]
shell = ["fish", "-c"]
true-color = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.smart-tab]
enable = false

[keys.normal]
J = "goto_word" 
K = "toggle_comments"
H = "goto_line_start"
L = "goto_line_end"

X = "extend_line_above"

w = "extend_next_word_start"
W = "extend_next_long_word_start"
C-w = "extend_next_sub_word_start"
b = "extend_prev_word_start"
B = "extend_prev_long_word_start"
C-b = "extend_prev_sub_word_start"
e = "extend_next_word_end"
E = "extend_next_long_word_end"
C-e = "extend_next_sub_word_end"

C-t = "extend_till_char"
C-f = "extend_next_char"

D = ["collapse_selection", "extend_to_line_end", "delete_selection"]
C-d = "delete_selection_noyank"
C = ["collapse_selection", "extend_to_line_end", "change_selection"]
C-c = "change_selection_noyank"

esc = "collapse_selection"
minus = "join_selections_space"
_ = "join_selections"
z = "flip_selections"
s = "copy_selection_on_next_line"
S = "select_regex"
q = "split_selection_on_newline"
Q = "split_selection"
C-q = "keep_selections"

tab = ":buffer-next"
S-tab = ":buffer-previous"

"~" = "switch_case"
"`" = "switch_to_lowercase"

"\"" = "no_op"
"'" = "no_op"
";" = "no_op"

# TODO: Send language with https://github.com/helix-editor/helix/pull/6979
"=" = ":pipe-to $HOME/.config/tmux/repl.sh" # Send selection to REPL
"+" = "@map=<esc>" # Send paragraph to REPL

[keys.select]
H = "goto_line_start"
L = "goto_line_end"
X = "extend_line_above"

t = "extend_till_char"
T = "extend_till_prev_char"
f = "extend_next_char"
F = "extend_prev_char"

C-w = "extend_next_sub_word_start"
C-b = "extend_prev_sub_word_start"
C-e = "extend_next_sub_word_end"

z = "flip_selections"

# TODO: See above
"=" = ":pipe-to $HOME/.config/tmux/repl.sh" # Send selection to REPL

[keys.insert]
# Apparently the best way to do this,
# https://github.com/helix-editor/helix/discussions/8258
S-tab = ":insert-output echo -ne '\t'"

[keys.normal.space]
a = "file_picker_in_current_directory"
b = "buffer_picker"
j = "jumplist_picker"
s = "global_search"
space = "file_picker"
"?" = "command_palette"

d = "no_op"
D = "no_op"
f = "no_op"
F = "no_op"
g = "no_op"
h = "no_op"
k = "no_op"
S = "no_op"
r = "no_op"
R = "no_op"
w = "no_op"
A-c = "no_op"
"'" = "no_op"
"/" = "no_op"

[keys.normal.backspace]
backspace = "select_register"

c = "replace_selections_with_clipboard"
C = "replace_selections_with_primary_clipboard"

q = "replay_macro"
Q = "record_macro"

[keys.normal.ret]
a = "code_action"
d = "diagnostics_picker"
D = "workspace_diagnostics_picker"
h = "select_references_to_symbol_under_cursor"
k = "hover"
s = "symbol_picker"
S = "workspace_symbol_picker"
r = "rename_symbol"
