theme = "everforest_dark"

[editor]
auto-pairs = false
line-number = "relative"
mouse = false
true-color = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
X = "extend_line_above"
w = "extend_next_word_start"
W = "extend_next_long_word_start"
b = "extend_prev_word_start"
B = "extend_prev_long_word_start"
D = ["collapse_selection", "kill_to_line_end"]
# C = ["collapse_selection", "extend_to_line_end", "change_selection"] # Broken, see github.com/helix-editor/helix/issues/2051