theme = "catppuccin_frappe"

[editor]
auto-pairs = false
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
mouse = false
rulers = [81]
shell = ["fish", "-c"]
true-color = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
X = "extend_line_above"
w = "extend_next_word_start"
W = "extend_next_long_word_start"
b = "extend_prev_word_start"
B = "extend_prev_long_word_start"
e = "extend_next_word_end"
E = "extend_next_long_word_end"
S = "copy_selection_on_next_line"
D = ["collapse_selection", "extend_to_line_end", "delete_selection"]
C = ["collapse_selection", "extend_to_line_end", "change_selection"]
K = "no_op" # Reminder to remap for something useful
";" = "repeat_last_motion"
"esc" = "collapse_selection"
"~" = "switch_to_uppercase"
# TODO: Send language with https://github.com/helix-editor/helix/pull/6979
"ret" = ":pipe-to $HOME/.config/tmux/repl.sh"

[keys.select]
"ret" = ":pipe-to $HOME/.config/tmux/repl.sh"

[keys.normal.z]
"s" = "split_selection_on_newline"
"S" = "split_selection"
"k" = "keep_selections"
"K" = "remove_selections"
"p" = "copy_selection_on_next_line"
"P" = "copy_selection_on_prev_line"
"f" = "flip_selections"
"F" = "ensure_selections_forward"
"t" = "no_op"
"b" = "no_op"
"m" = "no_op"
"up" = "no_op"
"down" = "no_op"
"c" = "no_op"
"z" = "no_op"
"j" = "no_op"
"pageup" = "no_op"
"pagedown" = "no_op"
"space" = "no_op"
"ret" = "no_op"
"backspace" = "no_op"
"C-b" = "no_op"
"C-u" = "no_op"
"C-f" = "no_op"
"C-d" = "no_op"
